### ISSUE TITLE
x86_64-apple-darwin13.4.0-ranlib does not work on macOS 10.11.6, "dyld: lazy symbol binding failed: Symbol not found: _clock_gettime"

### ISSUE THREAD

**Issue by phil-blain** [conda-forge/cctools-and-ld64-feedstock#47]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: It seems ranlib does not work anymore on 10.11.6, I get an error from dyld about "_clock_gettime":

~~~bash
$ x86_64-apple-darwin13.4.0-ar  cru libz.a libz_a-adler32.o libz_a-compress.o \
libz_a-crc32.o libz_a-deflate.o libz_a-gzread.o libz_a-gzclose.o libz_a-gzwrite.o \
libz_a-gzlib.o libz_a-infback.o libz_a-inffast.o libz_a-inflate.o libz_a-inftrees.o \
libz_a-trees.o libz_a-uncompr.o libz_a-zutil.o
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/Philippe/Code/gdb-feedstock/miniforge3/envs/test-cctools/bin/x86_64-apple-darwin13.4.0-ranlib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/Philippe/Code/gdb-feedstock/miniforge3/envs/test-cctools/bin/x86_64-apple-darwin13.4.0-ranlib
  Expected in: /usr/lib/libSystem.B.dylib

fatal error: x86_64-apple-darwin13.4.0-ar: fatal error in /Users/Philippe/Code/gdb-feedstock/miniforge3/envs/test-cctools/bin/x86_64-apple-darwin13.4.0-ranlib
~~~

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/Philippe/Code/gdb-feedstock/miniforge3/envs/test-cctools:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.10.8            h033912b_0    conda-forge
cctools_osx-64            973.0.1              h609b070_5    conda-forge
ld64_osx-64               609                  hc6b1d1e_5    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libllvm12                 12.0.1               hd011deb_2    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
sigtool                   0.1.3                h88f4db0_0    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test-cctools
    active env location : /Users/Philippe/Code/gdb-feedstock/miniforge3/envs/test-cctools
            shell level : 3
       user config file : /Users/Philippe/.condarc
 populated config files : /Users/Philippe/Code/gdb-feedstock/miniforge3/.condarc
                          /Users/Philippe/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.7
         python version : 3.9.7.final.0
       virtual packages : __osx=10.11.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/Philippe/Code/gdb-feedstock/miniforge3  (writable)
      conda av data dir : /Users/Philippe/Code/gdb-feedstock/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/Philippe/Code/gdb-feedstock/miniforge3/pkgs
                          /Users/Philippe/.conda/pkgs
       envs directories : /Users/Philippe/Code/gdb-feedstock/miniforge3/envs
                          /Users/Philippe/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by phil-blain** [comment]
I'm guessing this is due to https://github.com/conda-forge/cctools-and-ld64-feedstock/pull/40/commits/f9b541b36e241d8e93591c5d5c331f21e26608e3 (from #41) and  the fact that `_POSIX_TIMERS` is defined even if `clock_gettime()` is not (from https://github.com/pocoproject/poco/issues/1453#issuecomment-265214390)...

**Comment by isuruf** [comment]
https://github.com/tpoechtrager/cctools-port/pull/116

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/cctools-and-ld64-feedstock/pull/51

**Comment by phil-blain** [comment]
Thanks @isuruf ! :)
